Traceback (most recent call last):
  File "C:\Users\Panther\AppData\Local\Programs\Python\Python39\Lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\Panther\AppData\Local\Programs\Python\Python39\Lib\site-packages\nbclient\client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Panther\AppData\Local\Programs\Python\Python39\Lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\Panther\AppData\Local\Programs\Python\Python39\Lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\Panther\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\Panther\AppData\Local\Programs\Python\Python39\Lib\site-packages\nbclient\client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Panther\AppData\Local\Programs\Python\Python39\Lib\site-packages\nbclient\client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Users\Panther\AppData\Local\Programs\Python\Python39\Lib\site-packages\nbclient\client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from matplotlib import rcParams, cycler
import matplotlib.pyplot as plt
import numpy as np
plt.ion()
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mImportError[0m                               Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_3920/2191868119.py[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [1;32mfrom[0m [0mmatplotlib[0m [1;32mimport[0m [0mrcParams[0m[1;33m,[0m [0mcycler[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      2[0m [1;32mimport[0m [0mmatplotlib[0m[1;33m.[0m[0mpyplot[0m [1;32mas[0m [0mplt[0m[1;33m[0m[1;33m[0m[0m
[0;32m      3[0m [1;32mimport[0m [0mnumpy[0m [1;32mas[0m [0mnp[0m[1;33m[0m[1;33m[0m[0m
[0;32m      4[0m [0mplt[0m[1;33m.[0m[0mion[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\AppData\Local\Programs\Python\Python39\Lib\site-packages\matplotlib\__init__.py[0m in [0;36m<module>[1;34m[0m
[0;32m    105[0m [1;31m# cbook must import matplotlib only within function[0m[1;33m[0m[1;33m[0m[0m
[0;32m    106[0m [1;31m# definitions, so it is safe to import from it here.[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 107[1;33m [1;32mfrom[0m [1;33m.[0m [1;32mimport[0m [0m_api[0m[1;33m,[0m [0mcbook[0m[1;33m,[0m [0mdocstring[0m[1;33m,[0m [0mrcsetup[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    108[0m [1;32mfrom[0m [0mmatplotlib[0m[1;33m.[0m[0mcbook[0m [1;32mimport[0m [0mMatplotlibDeprecationWarning[0m[1;33m,[0m [0msanitize_sequence[0m[1;33m[0m[1;33m[0m[0m
[0;32m    109[0m [1;32mfrom[0m [0mmatplotlib[0m[1;33m.[0m[0mcbook[0m [1;32mimport[0m [0mmplDeprecation[0m  [1;31m# deprecated[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\AppData\Local\Programs\Python\Python39\Lib\site-packages\matplotlib\rcsetup.py[0m in [0;36m<module>[1;34m[0m
[0;32m     24[0m [1;32mfrom[0m [0mmatplotlib[0m [1;32mimport[0m [0m_api[0m[1;33m,[0m [0manimation[0m[1;33m,[0m [0mcbook[0m[1;33m[0m[1;33m[0m[0m
[0;32m     25[0m [1;32mfrom[0m [0mmatplotlib[0m[1;33m.[0m[0mcbook[0m [1;32mimport[0m [0mls_mapper[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 26[1;33m [1;32mfrom[0m [0mmatplotlib[0m[1;33m.[0m[0mcolors[0m [1;32mimport[0m [0mColormap[0m[1;33m,[0m [0mis_color_like[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     27[0m [1;32mfrom[0m [0mmatplotlib[0m[1;33m.[0m[0mfontconfig_pattern[0m [1;32mimport[0m [0mparse_fontconfig_pattern[0m[1;33m[0m[1;33m[0m[0m
[0;32m     28[0m [1;32mfrom[0m [0mmatplotlib[0m[1;33m.[0m[0m_enums[0m [1;32mimport[0m [0mJoinStyle[0m[1;33m,[0m [0mCapStyle[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\AppData\Local\Programs\Python\Python39\Lib\site-packages\matplotlib\colors.py[0m in [0;36m<module>[1;34m[0m
[0;32m     80[0m [1;32mimport[0m [0mmatplotlib[0m [1;32mas[0m [0mmpl[0m[1;33m[0m[1;33m[0m[0m
[0;32m     81[0m [1;32mimport[0m [0mnumpy[0m [1;32mas[0m [0mnp[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 82[1;33m [1;32mfrom[0m [0mmatplotlib[0m [1;32mimport[0m [0m_api[0m[1;33m,[0m [0mcbook[0m[1;33m,[0m [0mscale[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     83[0m [1;32mfrom[0m [1;33m.[0m[0m_color_data[0m [1;32mimport[0m [0mBASE_COLORS[0m[1;33m,[0m [0mTABLEAU_COLORS[0m[1;33m,[0m [0mCSS4_COLORS[0m[1;33m,[0m [0mXKCD_COLORS[0m[1;33m[0m[1;33m[0m[0m
[0;32m     84[0m [1;33m[0m[0m

[1;32m~\AppData\Local\Programs\Python\Python39\Lib\site-packages\matplotlib\scale.py[0m in [0;36m<module>[1;34m[0m
[0;32m     12[0m [1;33m[0m[0m
[0;32m     13[0m [1;32mimport[0m [0mnumpy[0m [1;32mas[0m [0mnp[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 14[1;33m [1;32mfrom[0m [0mnumpy[0m [1;32mimport[0m [0mma[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     15[0m [1;33m[0m[0m
[0;32m     16[0m [1;32mimport[0m [0mmatplotlib[0m [1;32mas[0m [0mmpl[0m[1;33m[0m[1;33m[0m[0m

[1;31mImportError[0m: cannot import name 'ma' from 'numpy' (unknown location)
ImportError: cannot import name 'ma' from 'numpy' (unknown location)

